username: javamanyy
name: javamanyy
#baseurl: /javamanyy
baseurl: /
markdown: redcarpet
safe: false
pygments: true
title: 歪言歪语
disqusname: javaman
motto: 在你所有的能耐中，至少应该有一样是拿得出手的。不会做很多事情并不可怕，可怕的是没有一件事情能做好。
subtitle: 红尘路上的行者歪歪
